[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170724213527-c4b2de4/master-haskell-20170724213527-c4b2de4"
  version = 1
  sha1 = "09aa2a97367596116e8d12112bf68464919d4815"

[build.dist-7-8]
  GHC_VERSION="7.8.4"
  CABAL_VERSION="1.24.0.0"
  MAFIA_HAPPY = "true"
  CACHE = "true"

[build.dist-7-10]
  GHC_VERSION="7.10.2"
  CABAL_VERSION="1.24.0.0"
  MAFIA_HAPPY = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "mafia"
  CACHE = "true"

[build.dist-8-0]
  GHC_VERSION="8.0.1"
  CABAL_VERSION="1.24.0.0"
  MAFIA_HAPPY = "true"
  CACHE = "true"

[build.branches-7-8]
  GHC_VERSION = "7.8.4"
  CABAL_VERSION = "1.24.0.0"
  MAFIA_HAPPY = "true"
  CACHE = "true"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  MAFIA_HAPPY = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "mafia"
  CACHE = "true"

[build.branches-8-0]
  GHC_VERSION="8.0.1"
  CABAL_VERSION="1.24.0.0"
  MAFIA_HAPPY = "true"
  CACHE = "true"
